# Generated by Django 2.1.4 on 2019-12-20 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.ImageField(max_length=200, upload_to='cars/%Y/%m', verbose_name='选择图片')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '轮播图展示课程',
                'verbose_name_plural': '轮播图展示课程',
            },
        ),
    ]
