# Generated by Django 2.1.4 on 2019-12-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('courses', '0002_loopitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='机构名称'),
        ),
    ]
