# Generated by Django 2.2 on 2019-11-28 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191128_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type', models.CharField(max_length=100, verbose_name='课程类型')),
                ('desc', models.CharField(max_length=200, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '类型名',
                'verbose_name_plural': '类型名',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseType', verbose_name='课程分类'),
        ),
    ]
