# Generated by Django 2.1.4 on 2019-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(db_index=True, default=None, max_length=64, verbose_name='openid'),
        ),
    ]
