# Generated by Django 2.2.7 on 2019-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191121_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(db_index=True, default=None, max_length=64, verbose_name='openid'),
        ),
    ]
