# Generated by Django 2.2 on 2019-11-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(max_length=80, verbose_name='用户头像'),
        ),
    ]
