# Generated by Django 2.2 on 2019-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(max_length=600, verbose_name='用户头像'),
        ),
    ]
