# Generated by Django 2.2.7 on 2019-11-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='hes_read',
            new_name='has_read',
        ),
    ]
