# Generated by Django 2.2 on 2019-11-30 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191128_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_auto_20191121_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('order_sn', models.CharField(max_length=500, verbose_name='订单编号')),
                ('pay_price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='支付金额')),
                ('pay_time', models.DateTimeField(verbose_name='支付时间')),
                ('created_time', models.DateTimeField(verbose_name='订单创建时间')),
                ('order_desc', models.CharField(max_length=300, verbose_name='订单描述')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
