# Generated by Django 2.2 on 2019-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_useropinion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useropinion',
            options={'verbose_name': '用户意见', 'verbose_name_plural': '用户意见'},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'verbose_name': '用户订单', 'verbose_name_plural': '用户订单'},
        ),
        migrations.AddField(
            model_name='userorder',
            name='is_Opinion',
            field=models.BooleanField(default=False, verbose_name='是否评价'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='is_Pay',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='order_Opinion',
            field=models.CharField(max_length=800, null=True, verbose_name='订单评价'),
        ),
    ]
