# Generated by Django 2.2 on 2019-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20191211_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_Opinion',
            field=models.CharField(max_length=800, verbose_name='订单评价'),
        ),
    ]
